### ISSUE TITLE
c2c should generate secrets for client endpoints using trust-store

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/module-ballerina-c2c#255]
**Description:**
c2c should generate secrets for client endpoints using Trust-store

```
final http:Client nettyEP = check new("https://netty:8688",
    secureSocket = {
        cert: {
            path: "./security/ballerinaTruststore.p12",
            password: "ballerina"
        },
        verifyHostName: false
    }
);
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
swan-lake-beta-1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anupama-pathirage** [comment]
@anuruddhal Why this is marked for Beta4 Milestone? Aren't we release this with Beta3.
