### ISSUE TITLE
Docker image generation failing on CI (git action)

### ISSUE THREAD

**Issue by bondowe** [ballerina-platform/module-ballerina-c2c#278]
**Description:**
Building an image on GitHub is failing with the error below.

```
error [k8s plugin]: module [myorg/mypkg:0.1.0] unable to build docker image: could not build image: failed to export image: failed to create image: failed to get layer sha256:29d030be9a9a9366c90ed4baba3f72b22f8d6a9015ff2adea63473b1cf51e993: layer does not exist
	@kubernetes:Docker 			 - complete 1/2 
	target/bin/mypkg.jar
```

Sample can be found at https://github.com/bondowe/balcode2cloud/runs/2920010835?check_suite_focus=true

**Suggested Labels:**
ci docker ballerina-platform

**Affected Product Version:**
slbeta1

**Comment by anuruddhal** [comment]
Hi @bondowe 

You have to add  `CI_BUILD` environment variable to use c2c in workflows.

```
env:
    CI_BUILD: true
```

**Comment by bondowe** [comment]
Thanks @anuruddhal. Setting the CI_BUILD env fixed it.
