### ISSUE TITLE
Support http:Listener parameters for expose annotation

### ISSUE THREAD

**Issue by Drifftr** [ballerina-platform/module-ballerina-c2c#368]
**Description:**
Requirement - For event api listeners generated through async api tool[1], we support int port (With default value), or http:Listener objects as input parameters for the Customized Listener object[2]. Its better if there is support for above scenarios (Default port value and http:Listener type) also for @cloud:Expose annotation.

**Describe your problem(s)**
Identify ports in all supported scenarios when using event api listeners generated through [async api tool](https://github.com/ballerina-platform/asyncapi/blob/listener-source/samplelistener/listener)

**Describe your solution(s)**
Add @cloud:Expose annotation support for parameter scenarios in [2].

[1]. https://github.com/ballerina-platform/asyncapi/blob/listener-source/samplelistener/listener
[2]. https://github.com/ballerina-platform/asyncapi/blob/listener-source/samplelistener/listener/listener.bal#L7

**Comment by xlight05** [comment]
Seems like we can't get the default value from the listener declaration. Created a separate issue for this.
https://github.com/ballerina-platform/module-ballerina-c2c/pull/374
