### ISSUE TITLE
Applying sorted content in Dockerfile

### ISSUE THREAD

**Issue by AchalaDias** [ballerina-platform/module-ballerina-c2c#414]
**Description:**
Each and every Ballerina c2c build generates Dockerfile content in different order. Even though the content is same the order of code lines are different.

**Describe your problem(s)**
Due to the above implementation we can't cache the layers and speed up deployment cycle in Choreo and always push as new layers to the container registry.

**Describe your solution(s)**
Generate the Dockerfile with sorted content (specifically copying layers).

**Comment by manjulaRathnayaka** [comment]
@anuruddhal Can we plz prioritize this ticket so that we can improve the UX of Choreo? The docker build and push takes around 45s and we believe we can reduce it up to 15s etc if this issue is fixed.

**Comment by anuruddhal** [comment]
@manjulaRathnayaka ack. We will start working on this.
