### ISSUE TITLE
Getting a class cast exception when I ran a simple C2C example

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/module-ballerina-c2c#500]
**Description:**
I had a simple HTTP client implemented in Ballerina, which works fine. But recently, I keep receiving the following error when I try to execute a simple `bal build`.

```sh
error: compilation failed: The compiler extension in package 'ballerina:cloud:2.1.2' failed to complete. class io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode cannot be cast to class io.ballerina.compiler.syntax.tree.MappingConstructorExpressionNode (io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode and io.ballerina.compiler.syntax.tree.MappingConstructorExpressionNode are in unnamed module of loader 'app')
```

I suspect the recent 2.1.2 release caused this.

**Steps to reproduce:**
Try a simple HTTP client with C2C.

**Affected Versions:**
- Ballerina 2201.0.1 (Swan Lake)
- macOS

**Comment by BuddhiWathsala** [comment]
Ballerina sample that I used.

```ballerina
import ballerina/http;

int port = 9090;

listener http:Listener securedEp = new (port, httpVersion = "2.0");

service /foo on securedEp {
    resource function get bar() returns string {
        return "Hello, World!";
    }
}
```

**Comment by BuddhiWathsala** [comment]
I even tried to run it offline, but the same issue returned.

**Comment by xlight05** [comment]
I'm not sure about this working earlier because I tested with 2022.0.1. still this issue is there. Anyhow, this we can't handle this variance references extensively as flow analysis not supported in ballerina. As a workaround, you can use certPath variable inline. 

For now I've prevented crash and added a warning in #501

**Comment by BuddhiWathsala** [comment]
Providing it inline won't be a sustainable solution since even in Choreo they have used these variables. Those are not just variables in Choreo use cases. They are using configurable variables. Those configurable variables cannot provide inline in a prod environment.

**Comment by anuruddhal** [comment]
@BuddhiWathsala 
The c2c module will ignore the configurable values and variables as the artifacts are generated at build time. 
For production environments, it is recommended to use Kustomize[1] on top of generated artifacts to configure the generated final yaml.

[1] https://kustomize.io/
