### ISSUE TITLE
Getting a compilation failure when I run a C2C example with SL Update 2

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/module-ballerina-c2c#509]
**Description:**
Getting the following error when I run a simple HTTP example.
```sh
Compiling source
        buddhi/ssl_issue_server:0.1.0
error: compilation failed: The compiler extension in package 'ballerina:cloud:2.1.3' failed to complete. null

```
**Steps to reproduce:**

**Affected Versions:**
SL Update 1 and 2

**OS, DB, other environment details and versions:**
- macOS
- Rancher v1.0.0

**Related Issues (optional):**
Blocker for this https://github.com/wso2-enterprise/internal-support-ballerina/issues/46

**Comment by BuddhiWathsala** [comment]
Seems related to this https://github.com/ballerina-platform/module-ballerina-c2c/issues/500

**Comment by BuddhiWathsala** [comment]
When I remove my variables and provide them inline, the issue got resolved.

```ballerina
import ballerina/io;
import ballerina/grpc;

// string certPath = "resources/public.crt";
// string keyPath = "resources/private.key";

listener grpc:Listener ep = new (8443,
    secureSocket = {
        key: {
            certFile: "resources/public.crt",
            keyFile: "resources/private.key"
        }
    }
);

@grpc:ServiceDescriptor {descriptor: ROOT_DESCRIPTOR_HELLO, descMap: getDescriptorMapHello()}
service "HelloWorld" on ep {

    remote function hello(string value) returns string|error {
        io:print(value);
        return string `Hello ${value}`;
    }
}
```
Since having a variable is a common thing in Ballerina apps, I think providing them inline wouldn't be a proper solution. We should properly fix this.

@anuruddhal @xlight05 WDYT?

**Comment by xlight05** [comment]
The above PR fixes the crash.
Yeah, since we cover some variable retrievals, its better to do the same for ssl config too. However, this requires some refactoring, will address it in another PR. #/511
