### ISSUE TITLE
Enable fatjar docker image

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/module-ballerina-c2c#632]
**Description:**
$Subject

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by sarindaSenevirathne** [comment]
hi @xlight05 after the discussion we had with @hevayo and Manjula Rathnayake, we provided the ETA as 31st January.
