### ISSUE TITLE
Create Video Series on Code to Cloud

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/module-ballerina-c2c#694]
**Description:**
$Subject - For youtube training series.
Script - https://github.com/ballerina-platform/module-ballerina-c2c/issues/674

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anuruddhal** [comment]
https://www.youtube.com/watch?v=AwK_FnCVT1Y
