### ISSUE TITLE
Implement `bal test --cloud` story

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/module-ballerina-c2c#695]
**Description:**
$Subject

This feature needs to be implemented for both JVM and GraalVM paths. The main idea of this feature is to ensure that the ballerina application runs just fine in the container as expected.

This has two user categories
1. Package Developers(Stdlib ...)
3. End users

This is mostly useful for stdlib teams to verify if all their features work smoothly in containers.  We have come across a similar situation where packages rely on os native libraries even in JVM path. This will only get worse in GraalVM approach. 

This is further useful when we experiment with smaller graalvm based images(alpine). 

**Describe your solution(s)**
C2C Plugin should generate dockerfiles accordingly to build and run test executables inside docker and do a docker run.

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Ramith-D-Rodrigo** [comment]
@xlight05 Can we close this issue?
