### ISSUE TITLE
Remove mostly static flag when --static was given

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/module-ballerina-c2c#735]
**Description:**
$Subject

will have to complete https://github.com/ballerina-platform/module-ballerina-c2c/issues/733 prior as of now mostly static flag is applied by the container, not the dockerfile.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by codingmickey** [comment]
Hey @xlight05! I would like work on this, but the issue isn't very clear from the description :(

**Comment by xlight05** [comment]
@codingmickey Thanks for your interest in Ballerina Hacktoberfest event =) Unfortunately, This issue is already resolved. We missed closing this issue. Please see if there's any other issue that interests you. I've added a new issue to hacktoberfest as well. You can take that issue if you like. =)

https://github.com/ballerina-platform/module-ballerina-c2c/issues/758
