### ISSUE TITLE
Add the "C2C" Module in SLAlpha1 API Docs

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/module-ballerina-c2c#75]
Add the "C2C" modules in SLAlpha1 API Docs[1].

[1] http://dev.ballerina.io/swan-lake/learn/api-docs/ballerina/#/

**Comment by shehan360** [comment]
Closing as this issue is fixed. 
http://dev.ballerina.io/swan-lake/learn/api-docs/ballerina/#/ballerina/cloud/1.0.0
