### ISSUE TITLE
Use subpaths to mount files

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/module-ballerina-c2c#780]
**Description:**
$Subject. This will help to mount individual files without conflicts to directories. 

Affected Fields
[[cloud.secret.files]]
[[cloud.config.maps]]

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anuruddhal** [comment]
Closing as this is implemented.
