### ISSUE TITLE
Ballerina Azure service bus connector daily build is failing with ballerina docker nightly image

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/module-ballerina-c2c#799]
**Description:**
> Ballerina Azure service bus connector daily build uses Ballerina docker (nightly) image and currently the build is failing as the nightly image does not contain the latest lang changes.

**Comment by keizer619** [comment]
This is updated pushed by Daily job
https://hub.docker.com/layers/ballerina/ballerina/nightly/images/sha256-530b4df439942e1ada935a264ec1bb92072e53b3c459cc3fa73befd07dad772f?context=explore
